INSERT INTO movie (`name`, `date`, description, category_id) VALUES 
('Le Parrain', '1972-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 1),
('Scarface', '1983-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 1),
('Les Affranchis', '1990-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 1),
('Heat', '1995-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 1),
('Die Hard', '1988-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 2),
('Demolition Man', '1993-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 2),
('Taken', '2008-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 2),
('Deadpool', '2016-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 2),
('Expandable', '1988-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 2),
('Scream', '1996-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 3),
('Vendredi 13', '1980-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 3),
('Saw', '2005-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 3),
('Scary Movie', '2000-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 3),
('Star Wars IV Un nouvel espoir', '1977-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 4),
('Alien', '1979-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 4),
('E.T', '1982-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 4),
('Robocop', '1987-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 4),
('The Game', '1997-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 5),
('Sixième Sens', '1999-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 5),
('Usual Suspects', '1995-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 5),
('Fight Club', '1999-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 5),
('Inception', '2010-01-01', 'lorem ipsum quia dolor sit amet, consectetur, adipisci velit', 5);movie